### ISSUE TITLE
Issues caused by owb_rmt_driver_info going out of scope

### ISSUE THREAD

**Issue by abraha2d** [DavidAntliff/esp32-owb#18]
The documentation for `owb_rmt_initialize` does not indicate that the `owb_rmt_driver_info` structure needs to be kept around, since the OneWireBus is actually a member of the info structure.

If the info structure goes out of scope, then things break down, and it's not apparent why. (I just spent a few hours tracking down an issue caused by this.)

**Comment by DavidAntliff** [comment]
@abraha2d I'm sorry you spent time tracking this down when better docs would have helped you avoid this. Thank you for reporting it. I will update the docs in due course and hopefully prevent anyone else having the same experience.

**Comment by abraha2d** [comment]
No worries, it was a good learning experience. Figured this will help others from encountering the same issue.

Thank you for the work with this one-wire driver, it's been very useful to me.
