### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Koxx3** [DavidAntliff/esp32-owb#23]
Hello,
this is very interesting !
Do you have an example using a Dallas/Maxim component with RMT please ?
Regards,
F.

**Comment by DavidAntliff** [comment]
How about this one?

https://github.com/DavidAntliff/esp32-ds18b20-example

It's an example of the DS18B20 one-wire temperature sensor using this component and RMT. Let me know if you have any questions.

**Comment by Koxx3** [comment]
thanks a lot. i'll try tomorrow 😉

**Comment by Koxx3** [comment]
hummmm ... unfortunatly, I use Arduino (big project) and it doesn't seems so eay to integrate espressig native SDK parts inside my project :(

**Comment by DavidAntliff** [comment]
Unfortunately I can't really provide any advice or support for the use of this within an Arduino project. Maybe someone else can help you - I'm sure other people have managed to wrap native SDK components for use with Arduino. I'll close this issue but feel free to comment further if you need to.
