### ISSUE TITLE
unable to read DS18B20 temperature while connected to wifi

### ISSUE THREAD

**Issue by futechiot** [DavidAntliff/esp32-owb#5]
hello.. there I just need one example using your library. I tried a lot but unable to compile code in Arduino.
can u please give me one example that works with esp32 while connected to wifi for arduino
?

**Comment by DavidAntliff** [comment]
[This](https://github.com/DavidAntliff/esp32-ds18b20) is an example using the DS18B20 with this library. However it's for the ESP-IDF, not for Arduino. You may be able to get it working with Arduino but I don't have any examples of this unfortunately.
